import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

const destinations = [
  {
    slug: "nepal",
    name: "Nepal",
    description: "Home to 8 of the world's 14 peaks over 8,000m, Nepal is the ultimate Himalayan destination. From the legendary Everest Base Camp to the diverse Annapurna Circuit, ancient temples in Kathmandu to jungle safaris in Chitwan — Nepal offers adventure, culture, and spirituality in equal measure.",
    image: "https://images.pexels.com/photos/38706090/pexels-photo-38706090.jpeg?auto=compress&w=1260&h=750&dpr=1",
    heroImage: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&w=1260&h=750&dpr=1",
    continent: "Asia",
    highlights: ["Mount Everest", "Annapurna Circuit", "Kathmandu Valley", "Chitwan National Park", "Pokhara Lakeside", "Buddhist Temples", "Sherpa Culture", "Rhododendron Forests"],
    bestTime: "Sep-Nov (autumn) for clear skies and mountain views. Mar-May (spring) for rhododendron blooms and warm temperatures. Dec-Feb is cold but clear. Jun-Aug is monsoon season — avoid unless you want lush green landscapes.",
    travelTips: "Get a TIMS card and national park permits before trekking. Hire licensed guides for restricted areas like Manaslu and Upper Mustang. Altitude sickness is real — acclimatize properly on high-altitude treks. Kathmandu's Thamel district is the hub for gear, food, and transport. Domestic flights to Lukla are weather-dependent — build buffer days.",
    places: [
      { name: "Kathmandu Valley", description: "Ancient capital with 7 UNESCO World Heritage Sites, including Pashupatinath, Boudhanath, and Swayambhunath.", image: "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&w=600" },
      { name: "Pokhara", description: "Lakeside city with stunning Annapurna views, adventure sports, and the gateway to the Annapurna Circuit.", image: "https://images.pexels.com/photos/2108845/pexels-photo-2108845.jpeg?auto=compress&w=600" },
      { name: "Everest Region", description: "The Khumbu Valley — home to Everest Base Camp, Namche Bazaar, and Tengboche Monastery.", image: "https://images.pexels.com/photos/38706090/pexels-photo-38706090.jpeg?auto=compress&w=600" },
      { name: "Chitwan National Park", description: "Jungle safari destination with rhinoceros, tigers, and exotic birds in the subtropical lowlands.", image: "https://images.pexels.com/photos/6790543/pexels-photo-6790543.jpeg?auto=compress&w=600" },
    ],
    gallery: [
      "https://images.pexels.com/photos/38706090/pexels-photo-38706090.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&w=1260",
    ],
    featured: true,
    order: 1,
  },
  {
    slug: "bhutan",
    name: "Bhutan",
    description: "The Land of the Thunder Dragon is one of the world's most exclusive travel destinations. With its pristine Himalayan landscapes, ancient Buddhist monasteries, and commitment to Gross National Happiness, Bhutan offers a truly unique travel experience.",
    image: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260&h=750&dpr=1",
    heroImage: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260&h=750&dpr=1",
    continent: "Asia",
    highlights: ["Tiger's Nest Monastery", "Punakha Dzong", "Thimphu Capital", "Paro Valley", "Gross National Happiness", "Buddhist Festivals", "Himalayan Passes", "Traditional Architecture"],
    bestTime: "Mar-May and Sep-Nov are best. Spring brings rhododendron blooms; autumn offers clear mountain views. Monsoon (Jun-Aug) is wet but green. Winter (Dec-Feb) is cold but quiet.",
    travelTips: "Bhutan charges a Sustainable Development Fee ($100/day for regional tourists, $200/day for international). All tours must be booked through licensed Bhutanese operators. Flights into Paro are limited and scenic. Dress modestly when visiting dzongs and monasteries. Alcohol is available but expensive.",
    places: [
      { name: "Paro Valley", description: "Home to the iconic Tiger's Nest Monastery and Paro Dzong, gateway to Bhutan.", image: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=600" },
      { name: "Thimphu", description: "The capital city with the giant Buddha statue, weekend market, and traditional arts center.", image: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=600" },
      { name: "Punakha", description: "The ancient capital with the magnificent Punakha Dzong at the confluence of two rivers.", image: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=600" },
      { name: "Bumthang Valley", description: "The spiritual heartland of Bhutan with ancient temples and pristine forests.", image: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=600" },
    ],
    gallery: [
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260",
    ],
    featured: true,
    order: 2,
  },
  {
    slug: "tibet",
    name: "Tibet",
    description: "The Roof of the World beckons with its vast high-altitude plateaus, ancient Buddhist monasteries, and the iconic Mount Everest north face. Tibet is a destination for those seeking profound cultural encounters and dramatic Himalayan scenery.",
    image: "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260&h=750&dpr=1",
    heroImage: "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260&h=750&dpr=1",
    continent: "Asia",
    highlights: ["Mount Everest North Base Camp", "Potala Palace", "Lhasa", "Mount Kailash", "Yamdrok Lake", "Buddhist Monasteries", "High Plateaus", "Nomadic Culture"],
    bestTime: "May-Oct is best. Jul-Aug is warmest but rainiest. Apr-May and Sep-Oct offer clear skies. Winter (Nov-Mar) is extremely cold and some areas close.",
    travelTips: "A Tibet Travel Permit is required (arranged through a licensed tour operator). Altitude is serious — Lhasa is 3,650m and Everest Base Camp is 5,200m. Acclimatize in Lhasa for 2-3 days before traveling further. Independent travel is not permitted — you must have a guide and vehicle. Bring warm layers even in summer.",
    places: [
      { name: "Lhasa", description: "The capital city with the iconic Potala Palace, Jokhang Temple, and Barkhor Street.", image: "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=600" },
      { name: "Everest North Base Camp", description: "The Tibetan side of Everest at 5,200m with views of the north face.", image: "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=600" },
      { name: "Yamdrok Lake", description: "One of Tibet's most sacred lakes with turquoise waters and mountain backdrop.", image: "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=600" },
    ],
    gallery: [
      "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260",
      "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260",
      "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260",
    ],
    featured: true,
    order: 3,
  },
  {
    slug: "india",
    name: "India",
    description: "From the desert forts of Rajasthan to the backwaters of Kerala, the Himalayan peaks of Ladakh to the beaches of Goa — India is a continent in itself. Rich in history, culture, and diversity, India offers some of the most vibrant and varied travel experiences on earth.",
    image: "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=1260&h=750&dpr=1",
    heroImage: "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=1260&h=750&dpr=1",
    continent: "Asia",
    highlights: ["Taj Mahal", "Rajasthan Palaces", "Kerala Backwaters", "Ladakh Himalayas", "Goa Beaches", "Varanasi Ghats", "Indian Cuisine", "Yoga & Wellness"],
    bestTime: "Oct-Mar is best for most of India (cool and dry). Apr-Jun is scorching in the plains but ideal for Ladakh and hill stations. Jul-Sep is monsoon — lush but wet. Goa is best Nov-Feb.",
    travelTips: "India is best experienced slowly — don't try to see everything in one trip. Train travel is an experience in itself (book AC classes). Street food is amazing but ease into it. Carry cash for small vendors — UPI payments are ubiquitous in cities. Dress modestly at temples and mosques. Hire guides at major monuments.",
    places: [
      { name: "Rajasthan", description: "Land of maharajas with pink Jaipur, blue Jodhpur, golden Jaisalmer, and lake Udaipur.", image: "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=600" },
      { name: "Kerala", description: "Tropical paradise with backwaters, houseboats, spice plantations, and Ayurvedic wellness.", image: "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=600" },
      { name: "Ladakh", description: "The 'Land of High Passes' with Buddhist monasteries, crystal lakes, and dramatic mountain landscapes.", image: "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=600" },
      { name: "Goa", description: "India's beach paradise with Portuguese heritage, seafood, nightlife, and laid-back vibes.", image: "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=600" },
    ],
    gallery: [
      "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg?auto=compress&w=1260",
    ],
    featured: false,
    order: 4,
  },
  {
    slug: "sri-lanka",
    name: "Sri Lanka",
    description: "The Pearl of the Indian Ocean packs an extraordinary variety into a compact island — ancient cities, lush tea plantations, pristine beaches, wildlife safaris, and warm hospitality. Sri Lanka is perfect for those who want diversity without the overwhelm of a larger country.",
    image: "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=1260&h=750&dpr=1",
    heroImage: "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=1260&h=750&dpr=1",
    continent: "Asia",
    highlights: ["Sigiriya Rock Fortress", "Tea Plantations", "Galle Fort", "Yala National Park", "Kandy Temple", "Ella Scenery", "Beaches", "Ancient Cities"],
    bestTime: "Dec-Apr is best for the west and south coasts. May-Sep is best for the east coast. The hill country is pleasant year-round. Apr is hot everywhere.",
    travelTips: "Get an Electronic Travel Authorization (ETA) before arrival. The train from Kandy to Ella is one of the world's most scenic rail journeys. Rent a tuk-tuk for the ultimate Sri Lankan road trip. Learn to say 'Ayubowan' (may you live long) — it opens doors everywhere. Sri Lankan rice and curry is a must.",
    places: [
      { name: "Sigiriya", description: "The iconic Lion Rock fortress with ancient frescoes and stunning views from the top.", image: "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=600" },
      { name: "Ella", description: "Hill country village with tea plantations, Nine Arches Bridge, and Ella Rock hiking.", image: "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=600" },
      { name: "Galle", description: "Historic Dutch colonial fort on the coast with boutique shops, cafes, and ramparts.", image: "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=600" },
      { name: "Yala National Park", description: "Premier wildlife park with leopards, elephants, and crocodiles.", image: "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=600" },
    ],
    gallery: [
      "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&w=1260",
    ],
    featured: false,
    order: 5,
  },
  {
    slug: "china",
    name: "China",
    description: "The Middle Kingdom is a land of staggering scale and diversity — from the Great Wall snaking across mountains to the karst peaks of Guilin, the futuristic skyline of Shanghai to the ancient warriors of Xi'an. China rewards those who venture beyond the obvious.",
    image: "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=1260&h=750&dpr=1",
    heroImage: "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=1260&h=750&dpr=1",
    continent: "Asia",
    highlights: ["Great Wall of China", "Forbidden City", "Terracotta Warriors", "Zhangjiajie Pillars", "Guilin Karst Peaks", "Shanghai Skyline", "Panda Sanctuaries", "Chinese Cuisine"],
    bestTime: "Apr-May and Sep-Oct are ideal for most of China. Jul-Aug is hot and rainy. Dec-Feb is cold but fewer tourists. Oct is best for the Great Wall.",
    travelTips: "Get a 144-hour transit visa exemption if eligible — covers Beijing, Shanghai, and more. Download WeChat and Alipay before arriving — cash is rarely used. A VPN is essential for Google, Instagram, and WhatsApp. Book train tickets 15 days in advance on 12306.cn. High-speed rail connects most major cities.",
    places: [
      { name: "Beijing", description: "Imperial capital with the Great Wall, Forbidden City, Temple of Heaven, and hutong alleys.", image: "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=600" },
      { name: "Shanghai", description: "Futuristic skyline, historic Bund, and the gateway to the Yangtze River Delta.", image: "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=600" },
      { name: "Guilin & Yangshuo", description: "Dramatic karst limestone peaks along the Li River — China's most iconic landscape.", image: "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=600" },
      { name: "Xi'an", description: "Ancient capital with the Terracotta Army, City Wall, and Muslim Quarter.", image: "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=600" },
    ],
    gallery: [
      "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=1260",
      "https://images.pexels.com/photos/2846217/pexels-photo-2846217.jpeg?auto=compress&w=1260",
    ],
    featured: false,
    order: 6,
  },
];

const packages = [
  // ─────────────────────────── TREKS ───────────────────────────
  {
    title: "Everest Base Camp Trek",
    description:
      "The Everest Base Camp Trek is the most iconic trekking route in the world. Starting with a dramatic flight to Lukla, you'll traverse the Khumbu Valley through Sherpa villages, ancient monasteries, and towering Himalayan peaks. The trail passes through Sagarmatha National Park — a UNESCO World Heritage Site — before reaching the base of the world's highest mountain at 5,364m. Along the way you'll acclimatize in Namche Bazaar, visit the famous Tengboche Monastery, and stand face-to-face with Everest, Lhotse, Nuptse, and Ama Dablam.",
    price: 1449,
    duration: 14,
    imageUrl: "https://images.pexels.com/photos/38706090/pexels-photo-38706090.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/38706090/pexels-photo-38706090.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 15,
    category: "trek",
    tag: "Popular Trek",
    rating: 4.9,
    reviewCount: 847,
    highlights: [
      "Stand at the base of Mount Everest (8,849m), the world's highest peak",
      "Scenic flight to Lukla with breathtaking Himalayan views",
      "Acclimatize in Namche Bazaar, the Sherpa capital",
      "Visit Tengboche Monastery with Everest backdrop",
      "Trek through Sagarmatha National Park, a UNESCO World Heritage Site",
      "Witness sunrise from Kala Patthar (5,545m) — best Everest panorama",
      "Experience authentic Sherpa culture and hospitality",
      "Pass through rhododendron and juniper forests",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport pickup and transfer to hotel in Thamel. Trek briefing and gear check.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Fly to Lukla, Trek to Phakding", description: "Early morning flight to Lukla (2,860m) with dramatic mountain views. Begin trekking along the Dudh Koshi River to Phakding.", trekTime: "3-4 hours", driveTime: "25 min flight", accommodation: "Tea House", elevation: "2,610m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Phakding" },
      { day: 3, title: "Phakding to Namche Bazaar", description: "Cross suspension bridges and climb steeply to Namche Bazaar, the gateway to Everest. First views of Everest on the trail.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,440m", distance: "11 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 4, title: "Acclimatization Day in Namche", description: "Rest day with optional hike to Everest View Hotel (3,880m) or Khumjung Village. Visit the Sherpa Museum and explore the bazaar.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "3,440m", distance: "7 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 5, title: "Namche to Tengboche", description: "Trek through rhododendron forest with views of Everest, Ama Dablam, and Nuptse. Visit Tengboche Monastery, the largest in the Khumbu.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,867m", distance: "9 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tengboche" },
      { day: 6, title: "Tengboche to Dingboche", description: "Descend through forest and cross the Imja River. Trek up the wide valley to the summer yak pastures of Dingboche.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "4,410m", distance: "11 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dingboche" },
      { day: 7, title: "Acclimatization Day in Dingboche", description: "Day hike to Nangkartshang Peak (5,083m) for panoramic views of Makalu, Lhotse, and Ama Dablam. Return to Dingboche.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "4,410m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dingboche" },
      { day: 8, title: "Dingboche to Lobuche", description: "Trek past the Dughla memorial cairns honoring fallen climbers. Ascend the terminal moraine of the Khumbu Glacier to Lobuche.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "4,940m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lobuche" },
      { day: 9, title: "Lobuche to Gorak Shep, Visit Everest Base Camp", description: "Trek to Gorak Shep and continue to Everest Base Camp (5,364m). Stand among the expedition tents with the Khumbu Icefall above. Return to Gorak Shep.", trekTime: "7-8 hours", driveTime: null, accommodation: "Tea House", elevation: "5,364m (BC)", distance: "13 km", meals: "Breakfast, Lunch, Dinner", overnight: "Gorak Shep" },
      { day: 10, title: "Gorak Shep to Kala Patthar, Trek to Pheriche", description: "Pre-dawn hike to Kala Patthar (5,545m) for the best sunrise panorama of Everest, Lhotse, and Nuptse. Descend to Pheriche.", trekTime: "7-8 hours", driveTime: null, accommodation: "Tea House", elevation: "4,240m", distance: "15 km", meals: "Breakfast, Lunch, Dinner", overnight: "Pheriche" },
      { day: 11, title: "Pheriche to Namche", description: "Long descent through familiar terrain back to Namche Bazaar. Celebrate the trek with the team.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "3,440m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 12, title: "Namche to Lukla", description: "Final day of trekking. Descend to Lukla through the Dudh Koshi valley. Farewell dinner with guides and porters.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "2,860m", distance: "19 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lukla" },
      { day: 13, title: "Fly to Kathmandu", description: "Morning flight back to Kathmandu. Free afternoon for shopping or sightseeing.", trekTime: null, driveTime: "25 min flight", accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 14, title: "Departure", description: "Airport transfer for your onward journey. Trip ends.", trekTime: null, driveTime: null, accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Annapurna Circuit Trek",
    description:
      "The Annapurna Circuit is one of the most diverse treks in the world. You'll traverse subtropical rice paddies, rhododendron forests, arid Tibetan-style plateaus, and cross the legendary Thorong La Pass at 5,416m — one of the highest trekking passes on earth. The circuit offers views of Annapurna I (8,091m), Dhaulagiri (8,167m), Manaslu (8,163m), and dozens of other peaks. You'll pass through Hindu villages, Buddhist monasteries, and the rain shadow desert of Upper Mustang.",
    price: 1449,
    duration: 14,
    imageUrl: "https://images.pexels.com/photos/1835718/pexels-photo-1835718.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/1835718/pexels-photo-1835718.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 15,
    category: "trek",
    tag: "Classic Route",
    rating: 4.8,
    reviewCount: 623,
    highlights: [
      "Cross Thorong La Pass at 5,416m — one of the world's highest trekking passes",
      "Circle the entire Annapurna Massif in one continuous route",
      "Experience every climate zone from subtropical jungle to high desert",
      "Views of Annapurna I, Dhaulagiri, Manaslu, and Machhapuchhre",
      "Visit the sacred temple at Muktinath (3,710m)",
      "Soak in natural hot springs at Tatopani",
      "Walk through the deepest gorge in the world — Kali Gandaki Valley",
      "Explore the medieval town of Manang",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport pickup and transfer to hotel. Trek briefing.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Drive to Chame", description: "Scenic drive from Kathmandu to Chame through the Marsyangdi Valley. Pass through terraced hillsides and pine forests.", trekTime: null, driveTime: "7-8 hours", accommodation: "Tea House", elevation: "2,670m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chame" },
      { day: 3, title: "Chame to Pisang", description: "Trek through dense forest with views of Annapurna II and Lamjung Himal. Pass through apple orchards and Manang villages.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,200m", distance: "15 km", meals: "Breakfast, Lunch, Dinner", overnight: "Pisang" },
      { day: 4, title: "Pisang to Manang", description: "Climb to the high plateau of Manang with panoramic views of the Annapurna range. Visit the Himalayan Rescue Association clinic.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,540m", distance: "16 km", meals: "Breakfast, Lunch, Dinner", overnight: "Manang" },
      { day: 5, title: "Acclimatization Day in Manang", description: "Day hike to Ice Lake (4,600m) or Gangapurna Lake. Rest and acclimatize before the high pass.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "3,540m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "Manang" },
      { day: 6, title: "Manang to Yak Kharka", description: "Gradual climb through juniper scrub and yak pastures. The landscape becomes increasingly barren and Tibetan in character.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "4,018m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Yak Kharka" },
      { day: 7, title: "Yak Kharka to Thorong Phedi", description: "Trek to the base of Thorong La. Final preparation for the pass crossing. Early dinner and early sleep.", trekTime: "3-4 hours", driveTime: null, accommodation: "Tea House", elevation: "4,525m", distance: "7 km", meals: "Breakfast, Lunch, Dinner", overnight: "Thorong Phedi" },
      { day: 8, title: "Cross Thorong La Pass to Muktinath", description: "Pre-dawn start for the biggest day of the trek. Climb to Thorong La (5,416m) and descend steeply to the sacred town of Muktinath.", trekTime: "8-10 hours", driveTime: null, accommodation: "Tea House", elevation: "3,710m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Muktinath" },
      { day: 9, title: "Muktinath to Jomsom", description: "Descend through the wind-swept Kali Gandaki Valley. Visit Muktinath Temple and the ancient monastery at Kagbeni.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "2,720m", distance: "20 km", meals: "Breakfast, Lunch, Dinner", overnight: "Jomsom" },
      { day: 10, title: "Jomsom to Tatopani", description: "Continue down the Kali Gandaki gorge. Soak in the natural hot springs at Tatopani (meaning 'hot water' in Nepali).", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "1,190m", distance: "22 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tatopani" },
      { day: 11, title: "Tatopani to Ghorepani", description: "Climb steeply through terraced rice paddies and rhododendron forest to the ridge village of Ghorepani.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "2,860m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghorepani" },
      { day: 12, title: "Ghorepani to Poon Hill, Trek to Nayapul, Drive to Pokhara", description: "Pre-dawn hike to Poon Hill (3,210m) for sunrise over the Annapurna and Dhaulagiri ranges. Descend to Nayapul and drive to Pokhara.", trekTime: "7-8 hours", driveTime: "1.5 hours", accommodation: "Hotel", elevation: "820m", distance: "20 km", meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 13, title: "Fly to Kathmandu", description: "Morning flight to Kathmandu. Free afternoon for sightseeing.", trekTime: null, driveTime: "25 min flight", accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 14, title: "Departure", description: "Airport transfer. Trip ends.", trekTime: null, driveTime: null, accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Manaslu Circuit Trek",
    description:
      "The Manaslu Circuit is often called the new Annapurna Circuit — offering the same diversity and grandeur but with a fraction of the crowds. This restricted-area trek circles Mt. Manaslu (8,163m), the world's eighth-highest peak, crossing the dramatic Larkya La Pass at 5,106m. The trail passes through Gurung villages, Tibetan Buddhist settlements, and pristine wilderness that feels untouched by modern tourism. It's a true adventure for those seeking solitude and authenticity.",
    price: 1099,
    duration: 13,
    imageUrl: "https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/35096919/pexels-photo-35096919.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 12,
    category: "trek",
    tag: "Restricted Area",
    rating: 4.8,
    reviewCount: 312,
    highlights: [
      "Circle the world's eighth-highest mountain (8,163m)",
      "Cross Larkya La Pass at 5,106m with panoramic views",
      "Trek through restricted area with fewer than 12,000 trekkers per year",
      "Experience Gurung and Tibetan Buddhist village life",
      "Walk through pristine rhododendron and bamboo forests",
      "View of Manaslu, Himlung Himal, Cheo Himal, and Annapurna II",
      "Visit ancient gompas and Buddhist monasteries",
      "Wilderness experience similar to Annapurna Circuit 30 years ago",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport transfer and trek briefing.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Drive to Machha Khola", description: "Long jeep drive through winding mountain roads to the trek starting point.", trekTime: null, driveTime: "8-9 hours", accommodation: "Tea House", elevation: "930m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Machha Khola" },
      { day: 3, title: "Machha Khola to Jagat", description: "Trek along the Budhi Gandaki River through subtropical forest and small villages.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "1,340m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Jagat" },
      { day: 4, title: "Jagat to Deng", description: "Cross the Budhi Gandaki on a suspension bridge and climb through forests. Enter the restricted area.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "1,804m", distance: "16 km", meals: "Breakfast, Lunch, Dinner", overnight: "Deng" },
      { day: 5, title: "Deng to Namrung", description: "Climb through dense forest with views opening up to Manaslu North. Pass through Tibetan Buddhist villages.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "2,660m", distance: "17 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namrung" },
      { day: 6, title: "Namrung to Samagaon", description: "Arrive at Samagaon with stunning views of Manaslu. Visit the Pungyen Gompa and mani walls.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "3,530m", distance: "16 km", meals: "Breakfast, Lunch, Dinner", overnight: "Samagaon" },
      { day: 7, title: "Acclimatization in Samagaon", description: "Day hike to Birendra Lake (3,450m) or visit the Manaslu Base Camp area. Rest and acclimatize.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "3,530m", distance: "6 km", meals: "Breakfast, Lunch, Dinner", overnight: "Samagaon" },
      { day: 8, title: "Samagaon to Samdo", description: "Trek through high-altitude pastures with views of Manaslu, Ngadi, and Larkye peaks.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "3,860m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Samdo" },
      { day: 9, title: "Samdo to Dharamsala (Larkya BC)", description: "Short trek to the stone shelter at Dharamsala. Prepare for the pass crossing tomorrow.", trekTime: "3-4 hours", driveTime: null, accommodation: "Tea House", elevation: "4,460m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dharamsala" },
      { day: 10, title: "Cross Larkya La to Bimthang", description: "The big day. Cross Larkya La Pass (5,106m) with panoramic views of Manaslu, Himlung Himal, and Annapurna II. Descend to Bimthang.", trekTime: "8-10 hours", driveTime: null, accommodation: "Tea House", elevation: "3,590m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Bimthang" },
      { day: 11, title: "Bimthang to Tilije", description: "Descend through rhododendron forest and rice paddies back to the Marsyangdi Valley.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "2,300m", distance: "17 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tilije" },
      { day: 12, title: "Tilije to Besisahar, Drive to Kathmandu", description: "Trek to the road head at Besisahar and drive back to Kathmandu.", trekTime: "3-4 hours", driveTime: "6-7 hours", accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast, Lunch", overnight: "Kathmandu" },
      { day: 13, title: "Departure", description: "Airport transfer. Trip ends.", trekTime: null, driveTime: null, accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Annapurna Base Camp Trek",
    description:
      "The Annapurna Base Camp trek is the perfect introduction to Himalayan trekking. In just 9 days you'll walk into the heart of the Annapurna Sanctuary — a natural amphitheater surrounded by 7,000m and 8,000m peaks including Annapurna I (8,091m) and the iconic Machhapuchhre (Fishtail). The trail passes through lush rhododendron forests, Gurung villages, and terraced farmland before entering the dramatic glacial basin of base camp. It's shorter than EBC but equally spectacular.",
    price: 799,
    duration: 9,
    imageUrl: "https://images.pexels.com/photos/35096919/pexels-photo-35096919.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/35096919/pexels-photo-35096919.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1835718/pexels-photo-1835718.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 15,
    category: "trek",
    tag: "Best Seller",
    rating: 4.8,
    reviewCount: 534,
    highlights: [
      "Stand inside a glacial amphitheater surrounded by 8,000m peaks",
      "See Annapurna I (8,091m) up close from base camp at 4,130m",
      "Witness the iconic Machhapuchhre (Fishtail) from multiple angles",
      "Trek through blooming rhododendron forests in spring",
      "Stay in traditional Gurung villages",
      "Soak in natural hot springs at Jhinu Danda",
      "One of the most accessible high-altitude treks in Nepal",
      "No technical climbing required — suitable for fit beginners",
    ],
    itinerary: [
      { day: 1, title: "Drive Kathmandu to Pokhara", description: "Scenic drive or flight to the lakeside city of Pokhara.", trekTime: null, driveTime: "6-7 hours", accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Dinner", overnight: "Pokhara" },
      { day: 2, title: "Drive to Nayapul, Trek to Ghandruk", description: "Drive to Nayapul and trek to the Gurung village of Ghandruk with Annapurna South views.", trekTime: "5-6 hours", driveTime: "1.5 hours", accommodation: "Tea House", elevation: "1,940m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghandruk" },
      { day: 3, title: "Ghandruk to Chomrong", description: "Descend and climb to Chomrong, the last major village before the Annapurna Sanctuary.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "2,170m", distance: "9 km", meals: "Breakfast, Lunch, Dinner", overnight: "Chomrong" },
      { day: 4, title: "Chomrong to Bamboo", description: "Descend steeply and trek through dense bamboo and rhododendron forest into the Sanctuary.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "2,310m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Bamboo" },
      { day: 5, title: "Bamboo to Deurali", description: "Continue up the Modi Khola valley. Pass through Himalaya Hotel and on to Deurali.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "3,174m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Deurali" },
      { day: 6, title: "Deurali to Annapurna Base Camp", description: "Trek via Machhapuchhre Base Camp (3,700m) into the Annapurna Sanctuary. Arrive at ABC (4,130m) with 360° mountain views.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "4,130m", distance: "9 km", meals: "Breakfast, Lunch, Dinner", overnight: "Annapurna Base Camp" },
      { day: 7, title: "ABC to Bamboo", description: "Descend from base camp through the sanctuary back to Bamboo.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "2,310m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Bamboo" },
      { day: 8, title: "Bamboo to Nayapul, Drive to Pokhara", description: "Trek to Jhinu Danda for hot springs, then continue to Nayapul. Drive to Pokhara.", trekTime: "5-6 hours", driveTime: "1.5 hours", accommodation: "Hotel", elevation: "820m", distance: "15 km", meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 9, title: "Return to Kathmandu", description: "Flight or drive back to Kathmandu. Trip ends.", trekTime: null, driveTime: "25 min flight", accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Langtang Valley Trek",
    description:
      "The Langtang Valley Trek is the shortest major trek in Nepal, yet it delivers a genuine Himalayan experience. Just a 7-hour drive from Kathmandu, you'll enter the Langtang Valley — a stunning U-shaped glacial valley bordered by 7,000m peaks. The trek passes through Langtang National Park, home to red pandas, Himalayan tahr, and over 300 bird species. You'll sleep in Tamang villages, cross glacial moraines, and stand at Kyanjin Gompa (3,870m) surrounded by some of Nepal's most beautiful mountains.",
    price: 690,
    duration: 8,
    imageUrl: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 15,
    category: "trek",
    tag: "Short Trek",
    rating: 4.7,
    reviewCount: 289,
    highlights: [
      "Trek just 7 hours drive from Kathmandu — most accessible major trek",
      "Enter the stunning Langtang glacial valley surrounded by 7,000m peaks",
      "Explore Kyanjin Gompa — an ancient Buddhist monastery at 3,870m",
      "Visit a local cheese factory at Kyanjin Gompa",
      "Walk through Langtang National Park — home to red pandas and Himalayan tahr",
      "Experience Tamang culture and hospitality",
      "Climb Tserko Ri (4,984m) for panoramic views of the Langtang range",
      "One of the most affordable Himalayan treks",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport transfer and trek briefing.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Drive to Syabrubesi", description: "Scenic drive through winding mountain roads to the trek starting point.", trekTime: null, driveTime: "7-8 hours", accommodation: "Tea House", elevation: "1,550m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Syabrubesi" },
      { day: 3, title: "Syabrubesi to Lama Hotel", description: "Trek through oak and rhododendron forest along the Langtang Khola.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "2,380m", distance: "13 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lama Hotel" },
      { day: 4, title: "Lama Hotel to Langtang Village", description: "Continue up the valley with views of Langtang Lirung (7,227m). Pass through forests and yak pastures.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,430m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Langtang Village" },
      { day: 5, title: "Langtang to Kyanjin Gompa", description: "Easy trek to Kyanjin Gompa (3,870m). Visit the monastery and cheese factory. Views of Langtang Lirung, Dorje Lakpa, and Gangchenpo.", trekTime: "3-4 hours", driveTime: null, accommodation: "Tea House", elevation: "3,870m", distance: "7 km", meals: "Breakfast, Lunch, Dinner", overnight: "Kyanjin Gompa" },
      { day: 6, title: "Kyanjin Gompa Exploration Day", description: "Optional climb to Tserko Ri (4,984m) or Kyanjin Ri (4,773m) for panoramic mountain views. Or rest and explore.", trekTime: "5-7 hours", driveTime: null, accommodation: "Tea House", elevation: "3,870m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "Kyanjin Gompa" },
      { day: 7, title: "Kyanjin Gompa to Lama Hotel", description: "Long descent back to Lama Hotel through the valley.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "2,380m", distance: "19 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lama Hotel" },
      { day: 8, title: "Lama Hotel to Syabrubesi, Drive to Kathmandu", description: "Trek to Syabrubesi and drive back to Kathmandu.", trekTime: "4-5 hours", driveTime: "7-8 hours", accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast, Lunch", overnight: null },
    ],
  },
  {
    title: "Mardi Himal Trek",
    description:
      "The Mardi Himal Trek is a hidden gem in the Annapurna region. This ridge-line trek offers intimate views of Machhapuchhre (Fishtail) and the Annapurna range without the crowds of ABC or Poon Hill. You'll walk through dense rhododendron forests, alpine meadows, and high-altitude ridges, reaching a viewpoint at 4,500m that puts you face-to-face with some of Nepal's most iconic peaks. It's short, affordable, and refreshingly uncrowded.",
    price: 475,
    duration: 7,
    imageUrl: "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/36478/amazing-beautiful-beauty-blue.jpg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 12,
    category: "trek",
    tag: "Off the Beaten Path",
    rating: 4.7,
    reviewCount: 178,
    highlights: [
      "Face-to-face views of Machhapuchhre (Fishtail) from the ridge",
      "Fewer crowds than ABC or Poon Hill — genuine solitude",
      "Trek through dense rhododendron forests to alpine ridges",
      "Reach 4,500m viewpoint without technical climbing",
      "See the full Annapurna range from a unique ridge perspective",
      "One of the most affordable treks in the Annapurna region",
      "Perfect 7-day trek for those with limited time",
      "Pass through traditional Gurung villages",
    ],
    itinerary: [
      { day: 1, title: "Drive Kathmandu to Pokhara", description: "Scenic drive to Pokhara.", trekTime: null, driveTime: "6-7 hours", accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Dinner", overnight: "Pokhara" },
      { day: 2, title: "Drive to Phedi, Trek to Forest Camp", description: "Drive to Phedi and trek through lush forest to Forest Camp.", trekTime: "4-5 hours", driveTime: "1 hour", accommodation: "Tea House", elevation: "2,500m", distance: "7 km", meals: "Breakfast, Lunch, Dinner", overnight: "Forest Camp" },
      { day: 3, title: "Forest Camp to Low Camp", description: "Climb through rhododendron forest with emerging mountain views.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "2,990m", distance: "6 km", meals: "Breakfast, Lunch, Dinner", overnight: "Low Camp" },
      { day: 4, title: "Low Camp to High Camp", description: "Above the treeline with panoramic views of Machhapuchhre and Annapurna South.", trekTime: "3-4 hours", driveTime: null, accommodation: "Tea House", elevation: "3,550m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "High Camp" },
      { day: 5, title: "High Camp to Base Camp and back to Low Camp", description: "Push to Mardi Himal viewpoint (4,500m) with stunning close-up views. Return to Low Camp.", trekTime: "7-8 hours", driveTime: null, accommodation: "Tea House", elevation: "2,990m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Low Camp" },
      { day: 6, title: "Low Camp to Sidhing, Drive to Pokhara", description: "Descend through forest to Sidhing and drive back to Pokhara.", trekTime: "4-5 hours", driveTime: "2-3 hours", accommodation: "Hotel", elevation: "820m", distance: "10 km", meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 7, title: "Return to Kathmandu", description: "Flight or drive back to Kathmandu.", trekTime: null, driveTime: "25 min flight", accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Poon Hill Trek",
    description:
      "The Poon Hill Trek is Nepal's most popular short trek — and for good reason. In just 5 days you'll climb through rhododendron forests and stone Gurung villages to the Poon Hill viewpoint (3,210m), where the sunrise over Dhaulagiri (8,167m), the Annapurna range, and Machhapuchhre (Fishtail) is one of the finest mountain panoramas on earth. It's beginner-friendly, affordable, and delivers an enormous amount of Himalaya in a short time.",
    price: 399,
    duration: 5,
    imageUrl: "https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/1004409/pexels-photo-1004409.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1835718/pexels-photo-1835718.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 20,
    category: "trek",
    tag: "Beginner Friendly",
    rating: 4.7,
    reviewCount: 456,
    highlights: [
      "Witness the iconic Poon Hill sunrise over the Annapurna and Dhaulagiri ranges",
      "Walk through massive rhododendron forests (spectacular in spring)",
      "Visit the traditional Gurung village of Ghandruk",
      "Reach 3,210m — no altitude sickness risk for most trekkers",
      "One of the most affordable treks in Nepal",
      "Perfect for first-time trekkers and families",
      "Comfortable teahouse accommodation throughout",
      "Just 5 days from Pokhara",
    ],
    itinerary: [
      { day: 1, title: "Pokhara to Tikhedhunga", description: "Drive to Nayapul and trek along the river to Tikhedhunga.", trekTime: "3-4 hours", driveTime: "1.5 hours", accommodation: "Tea House", elevation: "1,540m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tikhedhunga" },
      { day: 2, title: "Tikhedhunga to Ghorepani", description: "Climb the famous 3,000 stone steps to Ulleri, then through rhododendron forest to Ghorepani.", trekTime: "5-7 hours", driveTime: null, accommodation: "Tea House", elevation: "2,860m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghorepani" },
      { day: 3, title: "Poon Hill Sunrise, Trek to Tadapani", description: "Pre-dawn hike to Poon Hill (3,210m) for the legendary sunrise. Continue along the ridge to Tadapani.", trekTime: "6-7 hours", driveTime: null, accommodation: "Tea House", elevation: "2,630m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tadapani" },
      { day: 4, title: "Tadapani to Ghandruk", description: "Descend through forest to the Gurung village of Ghandruk. Explore the village and museum.", trekTime: "3-4 hours", driveTime: null, accommodation: "Tea House", elevation: "1,940m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghandruk" },
      { day: 5, title: "Ghandruk to Nayapul, Drive to Pokhara", description: "Descend to Nayapul and drive back to Pokhara.", trekTime: "4-5 hours", driveTime: "1.5 hours", accommodation: null, elevation: "820m", distance: "10 km", meals: "Breakfast, Lunch", overnight: null },
    ],
  },
  {
    title: "Everest Panorama Trek",
    description:
      "The Everest Panorama Trek is the shortest and easiest way to see Everest up close. In just 7 days you'll fly to Lukla, trek to Namche Bazaar, and hike to the Everest View Hotel at 3,880m — where you'll enjoy close-up views of Everest, Lhotse, Ama Dablam, and the surrounding peaks. You'll also visit Tengboche Monastery and experience Sherpa culture without the commitment of a full EBC trek.",
    price: 850,
    duration: 7,
    imageUrl: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/38706090/pexels-photo-38706090.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 15,
    category: "trek",
    tag: "Short Everest",
    rating: 4.6,
    reviewCount: 213,
    highlights: [
      "See Everest without the 14-day commitment of the full EBC trek",
      "Scenic flight to Lukla with dramatic mountain views",
      "Acclimatize in Namche Bazaar — the Sherpa capital",
      "Hike to the Everest View Hotel (3,880m) for close-up mountain views",
      "Visit Tengboche Monastery with Everest as the backdrop",
      "Experience authentic Sherpa culture and hospitality",
      "Perfect for those with limited time",
      "Lower altitude means less risk of altitude sickness",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport transfer and trek briefing.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Fly to Lukla, Trek to Phakding", description: "Scenic flight to Lukla. Trek along the Dudh Koshi River to Phakding.", trekTime: "3-4 hours", driveTime: "25 min flight", accommodation: "Tea House", elevation: "2,610m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Phakding" },
      { day: 3, title: "Phakding to Namche Bazaar", description: "Climb steeply to Namche Bazaar with first views of Everest.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,440m", distance: "11 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 4, title: "Acclimatization — Everest View Hotel", description: "Hike to the Everest View Hotel (3,880m) for panoramic views of Everest, Lhotse, and Ama Dablam. Return to Namche.", trekTime: "4-5 hours", driveTime: null, accommodation: "Tea House", elevation: "3,440m", distance: "7 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 5, title: "Namche to Tengboche", description: "Trek to Tengboche Monastery — the largest in the Khumbu. Everest views throughout.", trekTime: "5-6 hours", driveTime: null, accommodation: "Tea House", elevation: "3,867m", distance: "9 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tengboche" },
      { day: 6, title: "Tengboche to Lukla", description: "Long descent back to Lukla through familiar terrain.", trekTime: "7-8 hours", driveTime: null, accommodation: "Tea House", elevation: "2,860m", distance: "19 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lukla" },
      { day: 7, title: "Fly to Kathmandu", description: "Morning flight back to Kathmandu. Trip ends.", trekTime: null, driveTime: "25 min flight", accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  // ─────────────────────────── TOURS ───────────────────────────
  {
    title: "Kathmandu Pokhara Chitwan Tour",
    description:
      "The ultimate Nepal experience in 8 days. Explore the ancient temples and UNESCO World Heritage Sites of Kathmandu, relax by the lakeside in Pokhara with views of the Annapurna range, and go on a jungle safari in Chitwan National Park — home to one-horned rhinoceros, Bengal tigers, and exotic birds. This tour covers Nepal's three most iconic destinations in one seamless journey.",
    price: 990,
    duration: 8,
    imageUrl: "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/2108845/pexels-photo-2108845.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/6790543/pexels-photo-6790543.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 20,
    category: "tour",
    tag: "Cultural Tour",
    rating: 4.7,
    reviewCount: 389,
    highlights: [
      "Explore Kathmandu's UNESCO World Heritage Sites",
      "See Swayambhunath (Monkey Temple) and Boudhanath Stupa",
      "Relax on the shores of Phewa Lake in Pokhara",
      "Sunrise from Sarangkot with Annapurna views",
      "Jungle safari in Chitwan National Park",
      "Spot one-horned rhinoceros, tigers, and exotic birds",
      "Canoe ride on the Rapti River",
      "Experience traditional Tharu cultural dance",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport pickup and transfer to hotel. Welcome dinner at a traditional Nepali restaurant.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Kathmandu Sightseeing", description: "Visit Swayambhunath, Pashupatinath, Boudhanath, and Kathmandu Durbar Square.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 3, title: "Drive to Chitwan", description: "Scenic drive through the Terai lowlands to Chitwan National Park.", trekTime: null, driveTime: "5-6 hours", accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chitwan" },
      { day: 4, title: "Chitwan Jungle Safari", description: "Full day safari — jeep drive, canoe ride, jungle walk, bird watching. Visit the elephant breeding center.", trekTime: null, driveTime: null, accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chitwan" },
      { day: 5, title: "Drive to Pokhara", description: "Morning Tharu village visit. Drive to Pokhara along the scenic Prithvi Highway.", trekTime: null, driveTime: "5-6 hours", accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Pokhara" },
      { day: 6, title: "Pokhara Sightseeing", description: "Sunrise from Sarangkot. Visit World Peace Stupa, Davis Falls, Gupteshwor Cave. Boating on Phewa Lake.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast", overnight: "Pokhara" },
      { day: 7, title: "Drive to Kathmandu", description: "Scenic drive or flight back to Kathmandu. Free afternoon.", trekTime: null, driveTime: "6-7 hours", accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 8, title: "Departure", description: "Airport transfer. Trip ends.", trekTime: null, driveTime: null, accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Nepal Golden Triangle Tour",
    description:
      "The Nepal Golden Triangle covers three iconic destinations — Kathmandu, Pokhara, and Chitwan — with extra time to explore each one deeply. This 10-day journey gives you three full days in Kathmandu's temples and heritage sites, two days in Pokhara's lakeside paradise with mountain views, and two nights in the Chitwan jungle. It's the most comprehensive way to experience Nepal's cultural, natural, and wildlife highlights.",
    price: 1250,
    duration: 10,
    imageUrl: "https://images.pexels.com/photos/2108845/pexels-photo-2108845.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/2108845/pexels-photo-2108845.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/3581916/pexels-photo-3581916.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 15,
    category: "tour",
    tag: "Best Seller",
    rating: 4.8,
    reviewCount: 276,
    highlights: [
      "Explore all 7 UNESCO World Heritage Sites in Kathmandu Valley",
      "Private guided tours of Swayambhunath, Pashupatinath, and Boudhanath",
      "Sunrise from Nagarkot with Everest views",
      "Lakeside relaxation in Pokhara with Annapurna panorama",
      "Full-day jungle safari in Chitwan National Park",
      "Canoe ride, elephant breeding center, and Tharu cultural show",
      "Scenic drives through Nepal's diverse landscapes",
      "Most comprehensive Nepal tour available",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport pickup and hotel transfer.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Kathmandu Heritage Tour", description: "Visit Pashupatinath, Boudhanath, and Swayambhunath.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 3, title: "Nagarkot Day Trip", description: "Drive to Nagarkot for Himalayan sunrise views. Visit Bhaktapur Durbar Square.", trekTime: null, driveTime: "1 hour", accommodation: "Hotel", elevation: "2,175m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 4, title: "Drive to Chitwan", description: "Scenic drive to Chitwan. Afternoon Tharu village walk and cultural show.", trekTime: null, driveTime: "5-6 hours", accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chitwan" },
      { day: 5, title: "Chitwan Safari", description: "Full day jungle activities — jeep safari, canoe, jungle walk.", trekTime: null, driveTime: null, accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chitwan" },
      { day: 6, title: "Drive to Pokhara", description: "Drive to Pokhara. Afternoon free at lakeside.", trekTime: null, driveTime: "5-6 hours", accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Pokhara" },
      { day: 7, title: "Pokhara Sightseeing", description: "Sarangkot sunrise, World Peace Stupa, Davis Falls, boating on Phewa Lake.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast", overnight: "Pokhara" },
      { day: 8, title: "Pokhara Free Day", description: "Free day for paragliding, zip-lining, or exploring Pokhara.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast", overnight: "Pokhara" },
      { day: 9, title: "Drive to Kathmandu", description: "Scenic drive back to Kathmandu. Farewell dinner.", trekTime: null, driveTime: "6-7 hours", accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast, Dinner", overnight: "Kathmandu" },
      { day: 10, title: "Departure", description: "Airport transfer. Trip ends.", trekTime: null, driveTime: null, accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Chitwan Jungle Safari",
    description:
      "A 4-day immersion into Nepal's premier wildlife destination. Chitwan National Park is a UNESCO World Heritage Site and one of the best places in Asia to see wild rhinoceros, tigers, gharial crocodiles, and over 500 species of birds. You'll go on jeep safaris, canoe rides along the Rapti River, and nature walks with expert naturalists. The park's subtropical jungle is a world away from the mountains.",
    price: 350,
    duration: 4,
    imageUrl: "https://images.pexels.com/photos/6790543/pexels-photo-6790543.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/6790543/pexels-photo-6790543.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 20,
    category: "tour",
    tag: "Wildlife",
    rating: 4.6,
    reviewCount: 198,
    highlights: [
      "Spot one-horned rhinoceros and Bengal tigers in the wild",
      "Canoe ride on the Rapti River — see gharial crocodiles and water birds",
      "Guided nature walk through subtropical jungle",
      "Visit the elephant breeding center",
      "Bird watching — over 500 species recorded",
      "Experience Tharu cultural dance and village life",
      "UNESCO World Heritage Site",
      "All-inclusive lodge stay with meals",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Chitwan", description: "Drive or fly from Kathmandu/Pokhara. Check in to jungle lodge. Afternoon Tharu village walk and cultural show.", trekTime: null, driveTime: "5-6 hours", accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Lunch, Dinner", overnight: "Chitwan" },
      { day: 2, title: "Full Day Jungle Safari", description: "Jeep safari deep into the park. Look for rhinos, tigers, deer, and wild elephants. Canoe ride on the Rapti River.", trekTime: null, driveTime: null, accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chitwan" },
      { day: 3, title: "Jungle Walk and Bird Watching", description: "Guided nature walk with expert naturalist. Visit the elephant breeding center. Afternoon bird watching.", trekTime: null, driveTime: null, accommodation: "Jungle Lodge", elevation: "150m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Chitwan" },
      { day: 4, title: "Departure", description: "Morning free for a short walk or shopping. Drive or fly back to Kathmandu/Pokhara.", trekTime: null, driveTime: "5-6 hours", accommodation: null, elevation: "1,400m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Kathmandu Valley Heritage Tour",
    description:
      "Discover the ancient soul of Nepal's capital in this focused 3-day tour of Kathmandu Valley's UNESCO World Heritage Sites. From the golden temples of Patan to the incense-filled courtyards of Pashupatinath, from the all-seeing eyes of Boudhanath to the monkey-strewn hilltop of Swayambhunath — every day is a deep dive into one of the most culturally rich valleys on earth.",
    price: 250,
    duration: 3,
    imageUrl: "https://images.pexels.com/photos/3581916/pexels-photo-3581916.jpeg?auto=compress&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/3581916/pexels-photo-3581916.jpeg?auto=compress&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/2108845/pexels-photo-2108845.jpeg?auto=compress&w=1260&h=750&dpr=1",
    ],
    available: true,
    maxGroupSize: 20,
    category: "tour",
    tag: "Cultural Tour",
    rating: 4.6,
    reviewCount: 156,
    highlights: [
      "Visit all major UNESCO World Heritage Sites in Kathmandu",
      "Explore Swayambhunath (Monkey Temple) — the oldest stupa in Nepal",
      "Witness Hindu cremation rituals at Pashupatinath Temple",
      "Walk around the massive Boudhanath Stupa",
      "Explore the medieval city of Patan (Lalitpur)",
      "See Kathmandu Durbar Square's ancient royal palaces",
      "Expert local guide with deep cultural knowledge",
      "Short but immersive — perfect add-on to any Nepal trip",
    ],
    itinerary: [
      { day: 1, title: "Kathmandu Durbar Square & Swayambhunath", description: "Explore Kathmandu Durbar Square, Kumari House, and the ancient temples. Afternoon climb to Swayambhunath for sunset views.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 2, title: "Pashupatinath, Boudhanath & Patan", description: "Morning visit to Pashupatinath Temple (UNESCO). Walk around Boudhanath Stupa. Afternoon explore Patan Durbar Square.", trekTime: null, driveTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 3, title: "Bhaktapur & Nagarkot", description: "Day trip to medieval Bhaktapur and the hilltop town of Nagarkot for Himalayan views.", trekTime: null, driveTime: "1 hour", accommodation: null, elevation: "2,175m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing data (order matters for foreign keys)
  await prisma.review.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.package.deleteMany();
  await prisma.destination.deleteMany();

  // Seed destinations
  for (const dest of destinations) {
    await prisma.destination.create({ data: dest as any });
    console.log(`  ✓ Created destination: ${dest.name}`);
  }

  // Seed packages
  const nepalDest = destinations.find((d) => d.slug === "nepal");
  const nepalDestId = nepalDest ? (await prisma.destination.findUnique({ where: { slug: nepalDest.slug } }))?.id : null;
  for (const pkg of packages) {
    await prisma.package.create({ data: { ...pkg, destinationId: nepalDestId } as any });
    console.log(`  ✓ Created: ${pkg.title}${nepalDestId ? ` → linked to Nepal` : ""}`);
  }

  console.log(`\nDone! Seeded ${destinations.length} destinations and ${packages.length} packages.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
