import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

const packages = [
  {
    title: "Everest Base Camp Trek",
    description: "Walk in the footsteps of legends on the world's most iconic trek. Journey through Sherpa villages, ancient monasteries, and breathtaking Himalayan landscapes to the base of Mount Everest at 5,364m.",
    destination: "Nepal",
    price: 1894,
    duration: 14,
    imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Popular Trek",
    rating: 5,
    reviewCount: 55,
    maxGroupSize: 12,
    highlights: [
      "Stand at the base of the world's highest mountain at 5,364m",
      "Visit the famous Tengboche Monastery with Everest views",
      "Cross the dramatic Hillary Suspension Bridge",
      "Walk through authentic Sherpa villages and ancient culture",
      "Panoramic views of Lhotse, Nuptse, Ama Dablam, and more",
      "Experience the hospitality of Namche Bazaar, the Sherpa capital",
      "Witness sunrise over the Himalayas from Kala Patthar",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport pickup and transfer to hotel. Trek briefing and permit check.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Fly to Lukla, trek to Phakding", description: "Thrilling 35-minute mountain flight to Lukla. Begin trekking along the Dudh Koshi river through pine forests.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "2,610m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Phakding" },
      { day: 3, title: "Phakding to Namche Bazaar", description: "Cross suspension bridges and climb steeply to Namche Bazaar, the gateway to Everest. First views of Everest on a clear day.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,440m", distance: "11 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 4, title: "Acclimatization Day in Namche", description: "Rest day with optional hike to Everest View Hotel for panoramic views. Explore Namche market and Sherpa museum.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "3,440m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 5, title: "Namche to Tengboche", description: "Trek through rhododendron forest with stunning views of Ama Dablam. Visit the famous Tengboche Monastery.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,860m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tengboche" },
      { day: 6, title: "Tengboche to Dingboche", description: "Descend through forest to Debuche, cross the Imja Khola, and climb to Dingboche in the Imja Valley.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "4,410m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dingboche" },
      { day: 7, title: "Acclimatization Day in Dingboche", description: "Rest day with optional hike to Nagarjun Hill for views of Makalu, Lhotse, and Island Peak.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "4,410m", distance: "4 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dingboche" },
      { day: 8, title: "Dingboche to Lobuche", description: "Trek past the Dughla memorial cairns honoring fallen climbers. Ascend the terminal moraine of the Khumbu Glacier.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "4,940m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lobuche" },
      { day: 9, title: "Lobuche to Gorak Shep, visit Everest Base Camp", description: "Trek to Gorak Shep then continue to Everest Base Camp. Stand at the foot of the world's highest peak.", driveTime: null, trekTime: "7-8 hours", accommodation: "Tea House", elevation: "5,364m", distance: "13 km", meals: "Breakfast, Lunch, Dinner", overnight: "Gorak Shep" },
      { day: 10, title: "Gorak Shep to Kala Patthar, descend to Pheriche", description: "Early morning hike to Kala Patthar (5,545m) for the best sunrise views of Everest. Descend to Pheriche.", driveTime: null, trekTime: "7-8 hours", accommodation: "Tea House", elevation: "4,240m", distance: "15 km", meals: "Breakfast, Lunch, Dinner", overnight: "Pheriche" },
      { day: 11, title: "Pheriche to Namche", description: "Long descent retracing steps through Tengboche and down to Namche. Celebrate in Namche.", driveTime: null, trekTime: "6-7 hours", accommodation: "Tea House", elevation: "3,440m", distance: "20 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 12, title: "Namche to Lukla", description: "Final day of trekking. Descend through forests and bridges back to Lukla.", driveTime: null, trekTime: "6-7 hours", accommodation: "Tea House", elevation: "2,860m", distance: "19 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lukla" },
      { day: 13, title: "Fly Lukla to Kathmandu", description: "Morning flight back to Kathmandu. Free afternoon to explore the city.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 14, title: "Departure", description: "Airport transfer for your onward journey. Trek ends.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Manaslu Circuit Trek",
    description: "Circle the world's eighth highest mountain on this off-the-beaten-path adventure. Experience authentic Tibetan culture, cross the Larkya La pass at 5,106m, and trek through pristine wilderness.",
    destination: "Nepal",
    price: 986,
    duration: 13,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Off the Beaten Path",
    rating: 5,
    reviewCount: 366,
    maxGroupSize: 10,
    highlights: [
      "Circle the world's eighth highest mountain (8,163m)",
      "Cross the dramatic Larkya La Pass at 5,106m",
      "Experience authentic Tibetan Buddhist culture in remote villages",
      "Trek through pristine, crowd-free wilderness",
      "Stunning views of Manaslu, Himlung Himal, and Annapurna II",
      "Walk through the deepest gorge in the world — Budi Gandaki",
      "Explore ancient monasteries and prayer wheels",
    ],
    itinerary: [
      { day: 1, title: "Kathmandu to Machha Khola", description: "Long drive through scenic hills along the Budi Gandaki river.", driveTime: "9 hours", trekTime: null, accommodation: "Tea House", elevation: "930m", distance: "160 km", meals: "Lunch, Dinner", overnight: "Machha Khola" },
      { day: 2, title: "Machha Khola to Jagat", description: "Trek along the Budi Gandaki river through subtropical forests and Gurung villages.", driveTime: null, trekTime: "8 hours", accommodation: "Tea House", elevation: "1,340m", distance: "22 km", meals: "Breakfast, Lunch, Dinner", overnight: "Jagat" },
      { day: 3, title: "Jagat to Deng", description: "Enter the restricted area. Trek through Phillim and dense rhododendron forests.", driveTime: null, trekTime: "8 hours", accommodation: "Tea House", elevation: "1,804m", distance: "24 km", meals: "Breakfast, Lunch, Dinner", overnight: "Deng" },
      { day: 4, title: "Deng to Namrung", description: "Climb through bamboo and pine forests. Enter the Nubri valley with Tibetan culture.", driveTime: null, trekTime: "7-8 hours", accommodation: "Tea House", elevation: "2,630m", distance: "20 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namrung" },
      { day: 5, title: "Namrung to Shyala", description: "Stunning views of Manaslu open up. Trek through Lho with its ancient gompa.", driveTime: null, trekTime: "6 hours", accommodation: "Tea House", elevation: "3,575m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Shyala" },
      { day: 6, title: "Shyala to Sama Gaun", description: "Short trek to Sama Gaun, the main village of the Nubri people. Rest and explore.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "3,530m", distance: "9 km", meals: "Breakfast, Lunch, Dinner", overnight: "Sama Gaun" },
      { day: 7, title: "Acclimatization Day in Sama Gaun", description: "Day trip to Manaslu Base Camp or Pungyen Gompa for incredible mountain views.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "4,400m", distance: "11 km", meals: "Breakfast, Lunch, Dinner", overnight: "Sama Gaun" },
      { day: 8, title: "Sama Gaun to Samdo", description: "Trek through juniper and sparse forest to the Tibetan border village of Samdo.", driveTime: null, trekTime: "4-5 hours", accommodation: "Tea House", elevation: "3,860m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Samdo" },
      { day: 9, title: "Samdo to Dharamsala (Larkya BC)", description: "Short trek to the stone shelter at Dharamsala. Prepare for the pass crossing.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "4,460m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dharamsala" },
      { day: 10, title: "Cross Larkya La, descend to Bimthang", description: "Early start to cross the Larkya La pass (5,106m). Dramatic descent to Bimthang with incredible views.", driveTime: null, trekTime: "8-10 hours", accommodation: "Tea House", elevation: "3,590m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Bimthang" },
      { day: 11, title: "Bimthang to Dharapani", description: "Descend through beautiful forests and past waterfalls to Dharapani on the Annapurna Circuit.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "1,860m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dharapani" },
      { day: 12, title: "Dharapani to Kathmandu", description: "Drive back to Kathmandu through the Marsyangdi valley. Arrive evening.", driveTime: "9-10 hours", trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: "180 km", meals: "Breakfast, Lunch", overnight: "Kathmandu" },
      { day: 13, title: "Departure", description: "Airport transfer for your onward journey.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Annapurna Circuit Trek",
    description: "The classic Himalayan circuit takes you through diverse landscapes from subtropical forests to high alpine deserts. Cross the legendary Thorong La Pass at 5,416m with stunning Annapurna views.",
    destination: "Nepal",
    price: 1136,
    duration: 13,
    imageUrl: "https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Most Iconic Trek",
    rating: 5,
    reviewCount: 25,
    maxGroupSize: 12,
    highlights: [
      "Cross the legendary Thorong La Pass at 5,416m",
      "Trek through diverse landscapes from jungle to desert",
      "Visit the sacred Muktinath Temple",
      "Experience the natural hot springs at Tatopani",
      "Walk through the deepest gorge in the world — Kali Gandaki",
      "Stunning views of Annapurna, Dhaulagiri, and Manaslu",
      "Experience Gurung, Thakali, and Tibetan cultures",
    ],
    itinerary: [
      { day: 1, title: "Kathmandu to Besisahar", description: "Scenic drive along the Prithvi Highway to the trek starting point.", driveTime: "6-7 hours", trekTime: null, accommodation: "Tea House", elevation: "760m", distance: "180 km", meals: "Lunch, Dinner", overnight: "Besisahar" },
      { day: 2, title: "Besisahar to Bahundanda", description: "Trek through rice terraces and subtropical forests along the Marsyangdi river.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "1,310m", distance: "17 km", meals: "Breakfast, Lunch, Dinner", overnight: "Bahundanda" },
      { day: 3, title: "Bahundanda to Chamje", description: "Pass through waterfalls and villages. Cross suspension bridges over the Marsyangdi.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "1,410m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Chamje" },
      { day: 4, title: "Chamje to Dharapani", description: "Enter the Annapurna Conservation Area. Trek through forests and past the village of Tal.", driveTime: null, trekTime: "6-7 hours", accommodation: "Tea House", elevation: "1,860m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dharapani" },
      { day: 5, title: "Dharapani to Chame", description: "Trek through pine forests with views of Annapurna II and Lamjung Himal.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "2,670m", distance: "15 km", meals: "Breakfast, Lunch, Dinner", overnight: "Chame" },
      { day: 6, title: "Chame to Upper Pisang", description: "Walk through a deep forest past a stunning waterfall. Views of Annapurna II open up.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,300m", distance: "15 km", meals: "Breakfast, Lunch, Dinner", overnight: "Upper Pisang" },
      { day: 7, title: "Upper Pisang to Manang", description: "Trek along the ridge with panoramic views of the Annapurna range. Descend to Manang.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,540m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Manang" },
      { day: 8, title: "Acclimatization Day in Manang", description: "Day hike to Ice Lake or Gangapurna Lake for altitude adjustment. Visit the Himalayan Rescue Association.", driveTime: null, trekTime: "4-5 hours", accommodation: "Tea House", elevation: "3,540m", distance: "6 km", meals: "Breakfast, Lunch, Dinner", overnight: "Manang" },
      { day: 9, title: "Manang to Yak Kharka", description: "Gradual climb through sparse vegetation. Landscape becomes more barren and alpine.", driveTime: null, trekTime: "4-5 hours", accommodation: "Tea House", elevation: "4,018m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Yak Kharka" },
      { day: 10, title: "Yak Kharka to Thorong Phedi", description: "Final approach to the base of Thorong La. Prepare for the early pass crossing.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "4,525m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Thorong Phedi" },
      { day: 11, title: "Cross Thorong La, descend to Muktinath", description: "Pre-dawn start to cross Thorong La (5,416m). Steep descent to the sacred town of Muktinath.", driveTime: null, trekTime: "8-10 hours", accommodation: "Tea House", elevation: "3,800m", distance: "22 km", meals: "Breakfast, Lunch, Dinner", overnight: "Muktinath" },
      { day: 12, title: "Muktinath to Jomsom", description: "Trek through the windy Kali Gandaki valley. Visit Muktinath Temple before departing.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "2,720m", distance: "22 km", meals: "Breakfast, Lunch, Dinner", overnight: "Jomsom" },
      { day: 13, title: "Fly Jomsom to Pokhara", description: "Scenic morning flight along the Kali Gandaki to Pokhara. Rest and celebrate.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast", overnight: "Pokhara" },
    ],
  },
  {
    title: "Ghorepani Poonhill Trek",
    description: "Perfect for first-time trekkers and families. Wake up to a spectacular sunrise over the Annapurna and Dhaulagiri ranges from Poon Hill at 3,210m. Short, scenic, and unforgettable.",
    destination: "Nepal",
    price: 485,
    duration: 7,
    imageUrl: "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Kids Friendly",
    rating: 5,
    reviewCount: 11,
    maxGroupSize: 15,
    highlights: [
      "Witness a legendary sunrise over Annapurna and Dhaulagiri from Poon Hill",
      "Walk through charming Gurung villages and terraced hillsides",
      "Perfect short trek for families and first-time trekkers",
      "Stunning views of Machhapuchhre (Fishtail) and Annapurna South",
      "Trek through beautiful rhododendron forests",
      "Experience warm Gurung hospitality in Ghandruk",
      "Natural hot springs at Jhinu Danda",
    ],
    itinerary: [
      { day: 1, title: "Pokhara to Nayapul, trek to Tikhedhunga", description: "Drive to Nayapul and begin trekking through Birethanti village.", driveTime: "1.5 hours", trekTime: "4-5 hours", accommodation: "Tea House", elevation: "1,540m", distance: "10 km", meals: "Lunch, Dinner", overnight: "Tikhedhunga" },
      { day: 2, title: "Tikhedhunga to Ghorepani", description: "Climb the famous Ulleri stone steps. Trek through rhododendron forests to Ghorepani.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "2,860m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghorepani" },
      { day: 3, title: "Poon Hill Sunrise, trek to Tadapani", description: "Pre-dawn hike to Poon Hill (3,210m) for spectacular sunrise. Descend and trek to Tadapani.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "2,630m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tadapani" },
      { day: 4, title: "Tadapani to Ghandruk", description: "Descend through forests to the beautiful Gurung village of Ghandruk with mountain views.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "1,940m", distance: "9 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghandruk" },
      { day: 5, title: "Ghandruk to Jhinu Danda", description: "Descend stone steps to the Modi Khola river. End at natural hot springs.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "1,780m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Jhinu Danda" },
      { day: 6, title: "Jhinu Danda to Nayapul, drive to Pokhara", description: "Easy walk to Nayapul. Drive back to Pokhara. Free afternoon.", driveTime: "1.5 hours", trekTime: "3-4 hours", accommodation: "Hotel", elevation: "820m", distance: "10 km", meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 7, title: "Pokhara to Kathmandu", description: "Drive or fly back to Kathmandu. Trek ends.", driveTime: "6-7 hours", trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Langtang Valley Trek",
    description: "The closest trek to Kathmandu with stunning glacial valleys, Tamang culture, and panoramic Himalayan views. A short yet rewarding adventure through pristine rhododendron forests.",
    destination: "Nepal",
    price: 794,
    duration: 8,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Short & Scenic",
    rating: 5,
    reviewCount: 43,
    maxGroupSize: 12,
    highlights: [
      "Closest trek to Kathmandu — no flights needed",
      "Walk through pristine rhododendron and bamboo forests",
      "Experience rich Tamang and Tibetan Buddhist culture",
      "Panoramic views of Langtang Lirung (7,227m) and Ganesh Himal",
      "Explore the glacial valley of Kyanjin Gompa",
      "Taste local yak cheese at the Kyanjin dairy",
      "Visit the sacred Kyanjin Gompa monastery",
    ],
    itinerary: [
      { day: 1, title: "Kathmandu to Syabrubesi", description: "Scenic drive through winding mountain roads to the trek starting point.", driveTime: "7-8 hours", trekTime: null, accommodation: "Tea House", elevation: "1,550m", distance: "145 km", meals: "Lunch, Dinner", overnight: "Syabrubesi" },
      { day: 2, title: "Syabrubesi to Lama Hotel", description: "Trek through oak and rhododendron forests along the Langtang Khola.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "2,480m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lama Hotel" },
      { day: 3, title: "Lama Hotel to Langtang Village", description: "Continue up the valley with views of Langtang Lirung. Pass through Ghoda Tabela.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,430m", distance: "13 km", meals: "Breakfast, Lunch, Dinner", overnight: "Langtang Village" },
      { day: 4, title: "Langtang to Kyanjin Gompa", description: "Easy walk through yak pastures to Kyanjin Gompa. Visit the monastery and cheese factory.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "3,870m", distance: "7 km", meals: "Breakfast, Lunch, Dinner", overnight: "Kyanjin Gompa" },
      { day: 5, title: "Explore Kyanjin Gompa", description: "Day hike to Tserko Ri (4,984m) or Kyanjin Ri for panoramic views of the Langtang range.", driveTime: null, trekTime: "4-6 hours", accommodation: "Tea House", elevation: "3,870m", distance: "8 km", meals: "Breakfast, Lunch, Dinner", overnight: "Kyanjin Gompa" },
      { day: 6, title: "Kyanjin Gompa to Lama Hotel", description: "Descend back through the valley to Lama Hotel.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "2,480m", distance: "20 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lama Hotel" },
      { day: 7, title: "Lama Hotel to Syabrubesi", description: "Final day of trekking. Descend to Syabrubesi.", driveTime: null, trekTime: "4-5 hours", accommodation: "Tea House", elevation: "1,550m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Syabrubesi" },
      { day: 8, title: "Syabrubesi to Kathmandu", description: "Drive back to Kathmandu. Trek ends.", driveTime: "7-8 hours", trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast, Lunch", overnight: null },
    ],
  },
  {
    title: "Everest Base Camp with Helicopter Return",
    description: "Trek to Everest Base Camp and fly back in style. Save 4 days of walking while experiencing the best of the Khumbu region. Trek up, helicopter down — the perfect combination.",
    destination: "Nepal",
    price: 2449,
    duration: 11,
    imageUrl: "https://images.unsplash.com/photo-1516302752625-fcc3c50ae61f?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Premium",
    rating: 5,
    reviewCount: 3,
    maxGroupSize: 8,
    highlights: [
      "Trek to Everest Base Camp and fly back by helicopter",
      "Save 4 days of walking — the express route to EBC",
      "Land at Kala Patthar for photos of Everest",
      "All the highlights of the classic EBC trek in fewer days",
      "Scenic helicopter flight over the Khumbu region",
      "Perfect for those with limited time",
      "Exclusive small group experience",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Kathmandu", description: "Airport pickup and trek briefing.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Dinner", overnight: "Kathmandu" },
      { day: 2, title: "Fly to Lukla, trek to Namche", description: "Mountain flight to Lukla. Trek directly to Namche Bazaar.", driveTime: null, trekTime: "7-8 hours", accommodation: "Tea House", elevation: "3,440m", distance: "19 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 3, title: "Acclimatization in Namche", description: "Rest day with hike to Everest View Hotel.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "3,440m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "Namche Bazaar" },
      { day: 4, title: "Namche to Tengboche", description: "Trek to Tengboche with views of Ama Dablam.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,860m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tengboche" },
      { day: 5, title: "Tengboche to Dingboche", description: "Descend and climb to Dingboche in the Imja Valley.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "4,410m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dingboche" },
      { day: 6, title: "Acclimatization in Dingboche", description: "Day hike to Nagarjun Hill for mountain views.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "4,410m", distance: "4 km", meals: "Breakfast, Lunch, Dinner", overnight: "Dingboche" },
      { day: 7, title: "Dingboche to Lobuche", description: "Trek past memorial cairns to Lobuche.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "4,940m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lobuche" },
      { day: 8, title: "Lobuche to Gorak Shep, visit EBC", description: "Trek to Gorak Shep then continue to Everest Base Camp.", driveTime: null, trekTime: "7-8 hours", accommodation: "Tea House", elevation: "5,364m", distance: "13 km", meals: "Breakfast, Lunch, Dinner", overnight: "Gorak Shep" },
      { day: 9, title: "Kala Patthar, helicopter to Lukla", description: "Early morning Kala Patthar hike. Helicopter flight back to Lukla.", driveTime: null, trekTime: "2-3 hours", accommodation: "Tea House", elevation: "2,860m", distance: "5 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lukla" },
      { day: 10, title: "Fly Lukla to Kathmandu", description: "Morning flight back to Kathmandu.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 11, title: "Departure", description: "Airport transfer. Trek ends.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Tiger's Nest Monastery Trek",
    description: "Visit Bhutan's most sacred site, the cliff-hanging Tiger's Nest Monastery (Paro Taktsang). A cultural immersion into the Land of the Thunder Dragon with ancient temples and pristine forests.",
    destination: "Bhutan",
    price: 1250,
    duration: 5,
    imageUrl: "https://images.unsplash.com/photo-1553856622-d1b350672a56?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Cultural Trek",
    rating: 5,
    reviewCount: 18,
    maxGroupSize: 10,
    highlights: [
      "Visit the iconic Tiger's Nest Monastery clinging to a cliff face",
      "Experience Bhutan's unique Buddhist culture and traditions",
      "Explore ancient dzongs (fortresses) in Paro and Thimphu",
      "Walk through pristine Himalayan forests",
      "See traditional Bhutanese architecture and dress",
      "Learn about Gross National Happiness philosophy",
      "Taste authentic Bhutanese cuisine and butter tea",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Paro", description: "Fly into Paro (one of the world's most scenic landings). Transfer to hotel.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "2,200m", distance: null, meals: "Dinner", overnight: "Paro" },
      { day: 2, title: "Paro Sightseeing", description: "Visit Rinpung Dzong, Ta Dzong (National Museum), and Kyichu Lhakhang.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "2,200m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Paro" },
      { day: 3, title: "Tiger's Nest Monastery Trek", description: "Hike to Tiger's Nest (3,120m). The trail winds through blue pine forest to the sacred monastery.", driveTime: null, trekTime: "4-5 hours", accommodation: "Hotel", elevation: "3,120m", distance: "10 km", meals: "Breakfast, Lunch, Dinner", overnight: "Paro" },
      { day: 4, title: "Drive to Thimphu", description: "Scenic drive to the capital. Visit Tashichho Dzong and local markets.", driveTime: "1.5 hours", trekTime: null, accommodation: "Hotel", elevation: "2,320m", distance: "55 km", meals: "Breakfast, Lunch, Dinner", overnight: "Thimphu" },
      { day: 5, title: "Departure", description: "Airport transfer for your onward journey.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Kathmandu Valley Cultural Tour",
    description: "Explore the ancient temples, stupas, and palaces of the Kathmandu Valley. Visit UNESCO World Heritage Sites including Boudhanath, Pashupatinath, Swayambhunath, and Bhaktapur Durbar Square.",
    destination: "Nepal",
    price: 350,
    duration: 3,
    imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=500&fit=crop",
    category: "tour",
    tag: "Cultural Tour",
    rating: 5,
    reviewCount: 32,
    maxGroupSize: 15,
    highlights: [
      "Visit 4 UNESCO World Heritage Sites in one trip",
      "Explore the ancient city of Bhaktapur — the best-preserved medieval town",
      "Witness Hindu cremation rituals at Pashupatinath Temple",
      "Spin prayer wheels at the massive Boudhanath Stupa",
      "See panoramic valley views from Swayambhunath (Monkey Temple)",
      "Experience traditional Newari architecture and culture",
      "Guided by expert local historians",
    ],
    itinerary: [
      { day: 1, title: "Kathmandu Durbar Square & Swayambhunath", description: "Explore the ancient royal palace complex. Climb to Swayambhunath for sunset views.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast, Lunch", overnight: "Kathmandu" },
      { day: 2, title: "Pashupatinath & Boudhanath", description: "Morning at Pashupatinath Temple. Afternoon exploring the great stupa of Boudhanath.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast, Lunch", overnight: "Kathmandu" },
      { day: 3, title: "Bhaktapur & Patan", description: "Full day in Bhaktapur. Visit Patan Durbar Square on the way back.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast, Lunch", overnight: null },
    ],
  },
  {
    title: "Pokhara Adventure Tour",
    description: "Experience the adventure capital of Nepal. Paraglide over Phewa Lake, zip-line through forests, boat on the lake, and watch sunrise from Sarangkot with Machhapuchhre views.",
    destination: "Nepal",
    price: 692,
    duration: 4,
    imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&h=500&fit=crop",
    category: "tour",
    tag: "Adventure Tour",
    rating: 5,
    reviewCount: 27,
    maxGroupSize: 10,
    highlights: [
      "Tandem paragliding over Phewa Lake with Machhapuchhre views",
      "Sunrise from Sarangkot — one of Nepal's best viewpoints",
      "Zip-line through forests above Pokhara valley",
      "Boat ride on peaceful Phewa Lake",
      "Visit the World Peace Pagoda",
      "Explore Pokhara's lakeside restaurants and shops",
      "Optional ultralight flight over the Himalayas",
    ],
    itinerary: [
      { day: 1, title: "Kathmandu to Pokhara", description: "Fly or drive to Pokhara. Afternoon free to explore Lakeside.", driveTime: "6-7 hours", trekTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 2, title: "Sarangkot Sunrise & Paragliding", description: "Early drive to Sarangkot for sunrise. Tandem paragliding flight over the lake.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 3, title: "Boat Ride & World Peace Pagoda", description: "Boat ride on Phewa Lake. Hike to the World Peace Pagoda.", driveTime: null, trekTime: "2-3 hours", accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast, Lunch", overnight: "Pokhara" },
      { day: 4, title: "Pokhara to Kathmandu", description: "Free morning. Afternoon flight or drive back to Kathmandu.", driveTime: "6-7 hours", trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Lhasa & Tibet Cultural Tour",
    description: "Journey to the roof of the world. Visit the Potala Palace, Jokhang Temple, and Barkhor Street in Lhasa. Experience Tibetan Buddhist culture and stunning high-altitude landscapes.",
    destination: "Tibet",
    price: 1800,
    duration: 8,
    imageUrl: "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=800&h=500&fit=crop",
    category: "tour",
    tag: "Cultural Tour",
    rating: 5,
    reviewCount: 12,
    maxGroupSize: 8,
    highlights: [
      "Visit the iconic Potala Palace — the Dalai Lama's winter home",
      "Explore the sacred Jokhang Temple and Barkhor Street",
      "See Tibetan Buddhist monks debating at Sera Monastery",
      "Drive across the high Tibetan plateau (avg. 4,000m+)",
      "Visit Yamdrok Lake — one of Tibet's three holy lakes",
      "Experience authentic Tibetan Buddhist culture",
      "Expert Tibetan guides with deep cultural knowledge",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Lhasa", description: "Airport pickup. Gentle introduction to Lhasa at altitude.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "3,650m", distance: null, meals: "Dinner", overnight: "Lhasa" },
      { day: 2, title: "Acclimatization Day", description: "Easy walk around Lhasa. Visit local tea houses and acclimatize.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "3,650m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Lhasa" },
      { day: 3, title: "Potala Palace & Jokhang Temple", description: "Morning at the Potala Palace. Afternoon exploring Jokhang Temple and Barkhor Street.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "3,650m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Lhasa" },
      { day: 4, title: "Sera & Drepung Monasteries", description: "Visit Drepung Monastery. Afternoon at Sera for monk debates.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "3,650m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Lhasa" },
      { day: 5, title: "Lhasa to Yamdrok Lake", description: "Drive to Yamdrok Lake (4,441m). Spectacular turquoise lake with mountain views.", driveTime: "3 hours", trekTime: null, accommodation: "Hotel", elevation: "4,441m", distance: "130 km", meals: "Breakfast, Lunch, Dinner", overnight: "Nagartse" },
      { day: 6, title: "Yamdrok to Lhasa", description: "Morning at the lake. Drive back to Lhasa via Gyantse.", driveTime: "4 hours", trekTime: null, accommodation: "Hotel", elevation: "3,650m", distance: "260 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lhasa" },
      { day: 7, title: "Free Day in Lhasa", description: "Explore local markets, visit a tea house, or take a cooking class.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "3,650m", distance: null, meals: "Breakfast", overnight: "Lhasa" },
      { day: 8, title: "Departure", description: "Airport transfer for your onward journey.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Everest Helicopter Tour",
    description: "See Everest up close without trekking. Fly over the Khumbu Icefall, land at Kala Patthar for photos, and return in one thrilling morning. The ultimate Himalayan experience.",
    destination: "Nepal",
    price: 1499,
    duration: 1,
    imageUrl: "https://images.unsplash.com/photo-1516302752625-fcc3c50ae61f?w=800&h=500&fit=crop",
    category: "tour",
    tag: "Helicopter Tour",
    rating: 5,
    reviewCount: 9,
    maxGroupSize: 5,
    highlights: [
      "Land at Kala Patthar (5,545m) for Everest photos",
      "Fly over the famous Khumbu Icefall",
      "See Everest, Lhotse, Nuptse, and Ama Dablam up close",
      "Complete experience in just one day",
      "Champagne breakfast at Everest View Hotel",
      "Small group — maximum 5 passengers per helicopter",
      "No trekking required — perfect for all fitness levels",
    ],
    itinerary: [
      { day: 1, title: "Everest Helicopter Tour", description: "Early morning flight from Kathmandu. Fly over Lukla, Namche, and the Khumbu. Land at Kala Patthar for 20-30 minutes. Breakfast at Everest View Hotel. Return to Kathmandu by noon.", driveTime: null, trekTime: null, accommodation: null, elevation: "5,545m", distance: null, meals: "Breakfast", overnight: null },
    ],
  },
  {
    title: "Upper Mustang Trek",
    description: "Explore the forbidden kingdom of Lo Manthang. A remote, rain-shadow trek through arid landscapes, ancient cave dwellings, and Tibetan Buddhist monasteries in Nepal's last restricted region.",
    destination: "Nepal",
    price: 2200,
    duration: 16,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=500&fit=crop",
    category: "trek",
    tag: "Off the Beaten Path",
    rating: 5,
    reviewCount: 8,
    maxGroupSize: 8,
    highlights: [
      "Explore the ancient walled city of Lo Manthang",
      "Trek through Nepal's last restricted kingdom",
      "See 1,000-year-old cave dwellings and sky caves",
      "Experience authentic, untouched Tibetan Buddhist culture",
      "Walk through dramatic desert-like landscapes",
      "Visit ancient monasteries with rare murals and artifacts",
      "One of the most unique treks in the Himalayas",
    ],
    itinerary: [
      { day: 1, title: "Fly to Jomsom", description: "Scenic mountain flight from Pokhara to Jomsom along the Kali Gandaki.", driveTime: null, trekTime: null, accommodation: "Tea House", elevation: "2,720m", distance: null, meals: "Lunch, Dinner", overnight: "Jomsom" },
      { day: 2, title: "Jomsom to Kagbeni", description: "Trek along the windy Kali Gandaki river to the medieval village of Kagbeni.", driveTime: null, trekTime: "3-4 hours", accommodation: "Tea House", elevation: "2,810m", distance: "11 km", meals: "Breakfast, Lunch, Dinner", overnight: "Kagbeni" },
      { day: 3, title: "Kagbeni to Chele", description: "Enter the restricted area. Trek up the Kali Gandaki gorge.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,050m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Chele" },
      { day: 4, title: "Chele to Syangboche", description: "Cross two passes. Trek through dramatic red rock landscapes.", driveTime: null, trekTime: "6-7 hours", accommodation: "Tea House", elevation: "3,800m", distance: "16 km", meals: "Breakfast, Lunch, Dinner", overnight: "Syangboche" },
      { day: 5, title: "Syangboche to Ghami", description: "Cross La Phedi pass. Visit the longest mani wall in Nepal.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,520m", distance: "15 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghami" },
      { day: 6, title: "Ghami to Tsarang", description: "Descend to Tsarang with its red monastery and ancient fort.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,560m", distance: "14 km", meals: "Breakfast, Lunch, Dinner", overnight: "Tsarang" },
      { day: 7, title: "Tsarang to Lo Manthang", description: "Cross Lo La pass with first views of the walled city. Enter Lo Manthang.", driveTime: null, trekTime: "4-5 hours", accommodation: "Tea House", elevation: "3,840m", distance: "12 km", meals: "Breakfast, Lunch, Dinner", overnight: "Lo Manthang" },
      { day: 8, title: "Explore Lo Manthang", description: "Full day exploring the ancient city. Visit monasteries, royal palace, and local artisans.", driveTime: null, trekTime: null, accommodation: "Tea House", elevation: "3,840m", distance: null, meals: "Breakfast, Lunch, Dinner", overnight: "Lo Manthang" },
      { day: 9, title: "Lo Manthang to Ghami", description: "Begin return journey via alternative route.", driveTime: null, trekTime: "5-6 hours", accommodation: "Tea House", elevation: "3,520m", distance: "18 km", meals: "Breakfast, Lunch, Dinner", overnight: "Ghami" },
      { day: 10, title: "Ghami to Samar", description: "Continue descent through dramatic landscapes.", driveTime: null, trekTime: "6-7 hours", accommodation: "Tea House", elevation: "3,620m", distance: "20 km", meals: "Breakfast, Lunch, Dinner", overnight: "Samar" },
      { day: 11, title: "Samar to Jomsom", description: "Trek back to Jomsom through the Kali Gandaki valley.", driveTime: null, trekTime: "6-7 hours", accommodation: "Tea House", elevation: "2,720m", distance: "22 km", meals: "Breakfast, Lunch, Dinner", overnight: "Jomsom" },
      { day: 12, title: "Fly Jomsom to Pokhara", description: "Morning flight back to Pokhara.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast", overnight: "Pokhara" },
      { day: 13, title: "Pokhara Sightseeing", description: "Free day in Pokhara. Visit Phewa Lake, World Peace Pagoda, or go paragliding.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "820m", distance: null, meals: "Breakfast", overnight: "Pokhara" },
      { day: 14, title: "Pokhara to Kathmandu", description: "Drive or fly back to Kathmandu.", driveTime: "6-7 hours", trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 15, title: "Free Day in Kathmandu", description: "Explore Kathmandu at your leisure. Shopping, sightseeing, or relaxation.", driveTime: null, trekTime: null, accommodation: "Hotel", elevation: "1,400m", distance: null, meals: "Breakfast", overnight: "Kathmandu" },
      { day: 16, title: "Departure", description: "Airport transfer. Trek ends.", driveTime: null, trekTime: null, accommodation: null, elevation: null, distance: null, meals: "Breakfast", overnight: null },
    ],
  },
];

async function main() {
  console.log("Seeding packages...");

  for (const pkg of packages) {
    await prisma.package.upsert({
      where: { id: pkg.title.toLowerCase().replace(/[^a-z0-9]+/g, "-") },
      update: pkg,
      create: {
        id: pkg.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
        ...pkg,
      },
    });
  }

  console.log(`Seeded ${packages.length} packages.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
